### ISSUE TITLE
btyd library is dependent on lifetimes but doesn't install it.

### ISSUE THREAD

**Issue by s-pike** [ColtAllen/btyd#42]
I installed btyd using `pip install btyd`.

It installed with no errors. However, it won't import as I haven't installed the lifetimes library in that environment. I think the references need to be changed in [modified_beta_geo_fitter.py](https://github.com/ColtAllen/btyd/blob/main/btyd/fitters/modified_beta_geo_fitter.py)

Error message:
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Input In [1], in <cell line: 4>()
      2 import pandas as pd
      3 import numpy as np
----> 4 import btyd

File /libraries/CLTV/lib/python3.9/site-packages/btyd/__init__.py:6, in <module>
      4 from .fitters.beta_geo_fitter import BetaGeoFitter
      5 from .fitters.beta_geo_beta_binom_fitter import BetaGeoBetaBinomFitter
----> 6 from .fitters.modified_beta_geo_fitter import ModifiedBetaGeoFitter
      7 from .fitters.pareto_nbd_fitter import ParetoNBDFitter
      8 from .fitters.gamma_gamma_fitter import GammaGammaFitter

File /libraries/CLTV/lib/python3.9/site-packages/btyd/fitters/modified_beta_geo_fitter.py:11, in <module>
      8 from autograd.scipy.special import gammaln, beta, gamma
      9 from scipy.special import hyp2f1
---> 11 from lifetimes import BetaGeoFitter
     12 from lifetimes.generate_data import modified_beta_geometric_nbd_model
     15 class ModifiedBetaGeoFitter(BetaGeoFitter):

ModuleNotFoundError: No module named 'lifetimes'
```

Version: `btyd==0.1a1`

**Comment by ColtAllen** [comment]
Hey @s-pike,  thanks for bringing this to my attention. I think this is also causing issues with the doc builds, so I'll roll it into the current PR I'm working on for the documentation. I'll also look at the CI/CD scripts, because they should have caught this.

**Comment by ColtAllen** [comment]
This issue was fixed in https://github.com/ColtAllen/btyd/pull/43 and will be included in the Beta release.
