### ISSUE TITLE
Big data: pandas limitation 

### ISSUE THREAD

**Issue by joelcarvalhopribss** [ColtAllen/btyd#55]
Hi everyone!

Are there any workarounds for working with large datasets? When I load (in spark) some large dataset and try to convert it to pandas, this process may display an error or take a long time.

Thanks! 👍

**Comment by ColtAllen** [comment]
Hey @joelcarvalhopribss,

If the RAM requirements for your raw customer transactions exceed what's available in your compute instance, the only options are to either move to a larger compute resource, or do the RFM aggregations elsewhere. Memory should not be an issue after your data is in RFM format. I've worked with datasets consisting of multiple GB and over 87 million transactions, but after being aggregated into an RFM dataframe it was less than 40 MB.

The most straightforward approach is to create a view or table in your SQL database. There is some boilerplate SQL code in the documentation for doing so:

https://btyd.readthedocs.io/en/latest/Generate%20RFM%20Summaries%20From%20a%20SQL%20Store.html

If you're working with Spark, Databricks also has a notebook example for RFM processing:

https://www.databricks.com/notebooks/Customer%20Lifetime%20Value%20Virtual%20Workshop/02%20The%20BTYD%20Models.html

If you're using Snowflake, something else to try is applying `btyd.utils.summary_data_from_transaction_data` directly to your transaction data via Snowpark. I intend to add an example of this to the documentation in the future.

I just attended the Ray Summit this week for distributed processing, and would consider adding optional dependencies to speed up the RFM aggregations if popular demand decrees I do so. However it won't overcome the RAM limitation. `modin` (which runs on top of `ray`) would be almost a drop-in replacement, but would require a lot of additional dependency requirements. `dask` on the other hand is already available in many managed Python environments, but implementing `dask` would require significant refactoring.
