### ISSUE TITLE
Why monetary_val and monetary_holdout is missing?

### ISSUE THREAD

**Issue by SSMK-wq** [ColtAllen/btyd#68]
@ColtAllen - Why is that we don't see `monetary_val` for calibration and holdout when we use "calibration_and_holdout_data" utility function. You can see that when I use the above btyd or lifetimes function (both tried), it results in below table (monetary value is missing). Can help me understand what is wrong here? If it is not there by design, then how do we compare the monetary values for actual and holdout datasets (using gamma gamma distributions)?

For ex: Currently, am able to compare the frequency between actual holdout and predicted expected purchase as shown below

![image](https://user-images.githubusercontent.com/30723825/200529457-10bb8f27-8c39-4f34-8eac-2a48a63ed3a2.png)

But how can we do the same for monetary value (using Gamma gamma model) when we don't have monetary column value in the `calibration_and_holdout_data`? currently the table looks like below. I should do it locally?

![image](https://user-images.githubusercontent.com/30723825/200525901-8b3bcc0b-a161-417d-b9a6-730fe2f57d34.png)

one side question - I see that the duration in holdout dataset is 365 days. So, just to ensure proper comparison between actual and predicted values, I should set the `time horizon` in the model predict function also as 365 days. Am I right? I know based on business requirement, we can set different time horizons but to compare them correctly, we need to set as 365 days. Am I right?

**Comment by ColtAllen** [comment]
Hey @SSMK-wq, thanks for bringing this to my attention. Looks like an oversight in the legacy `lifetimes` library. I'll work on this for the v0.1b4 release.

 > I see that the duration in holdout dataset is 365 days. So, just to ensure proper comparison between actual and predicted values, I should set the time horizon in the model predict function also as 365 days. Am I right?

Yes

**Comment by ColtAllen** [comment]
Hey @SSMK-wq, I don't see a monetary value column being passed into `calibration_and_holdout_data` in your screenshots. It's an optional parameter and easy to overlook; have you tried that?
