### ISSUE TITLE
Question - How to get ITT or transaction rate of a customer?

### ISSUE THREAD

**Issue by SSMK-wq** [ColtAllen/btyd#72]
I am trying to know whether we can extract the transaction rate (lambda) of each customer through btyd package? By ITT, I mean Intra Transaction Time 

I know the algo uses transaction rate to predict/determine future values. Is it possible to get the transaction rate for each customer through btyd package (instead of us computing the average gap between transactions)? Am not sure whether our average computation (and transaction rate is one and the same). But would be good to verify the value that package/algo outputs

**Comment by ColtAllen** [comment]
Hey @SSMK-wq, lambda is actually represented by a probability distribution rather than a single estimated value. `from btyd.plotting import plot_transaction_rate_heterogeneity` will allow you to visualize this distribution.
